import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Loader, Printer, ArrowLeft, FileText } from 'lucide-react';
import api from '../utils/api';
import Button from '../components/ui/Button';

export default function ExportQuiz() {
  const { quizId } = useParams();
  const navigate = useNavigate();
  const [quiz, setQuiz] = useState(null);
  const [loading, setLoading] = useState(true);
  const [showAnswers, setShowAnswers] = useState(false);

  useEffect(() => {
    api.get(`/quiz/${quizId}`)
      .then(res => setQuiz(res.data))
      .catch(() => navigate('/dashboard'))
      .finally(() => setLoading(false));
  }, [quizId, navigate]);

  if (loading) return (
    <div className="min-h-screen bg-gray-100 p-4 md:p-8">
      <div className="max-w-4xl mx-auto">
        <div className="bg-white rounded-xl shadow-lg p-8">
          <div className="h-8 bg-gray-200 rounded-lg w-64 mb-4 animate-pulse"></div>
          <div className="space-y-4">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="p-4 border border-gray-200 rounded-lg">
                <div className="h-4 bg-gray-200 rounded-lg w-3/4 mb-2 animate-pulse"></div>
                <div className="h-3 bg-gray-100 rounded-lg w-1/2 animate-pulse"></div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-gray-100 p-4 md:p-8 print:p-0">
      {/* Toolbar (hidden when printing) */}
      <div className="max-w-3xl mx-auto mb-4 flex items-center justify-between print:hidden bg-dark-surface p-4 rounded-2xl border border-gray-800">
        <Button onClick={() => navigate(-1)} variant="ghost" size="sm" className="text-gray-400 hover:text-white">
          <ArrowLeft size={18} /> Back
        </Button>
        <div className="flex gap-2">
          <Button
            onClick={() => setShowAnswers(s => !s)}
            variant="outline"
            size="sm"
            className="border-gray-700 text-gray-300 hover:bg-gray-800"
          >
            {showAnswers ? 'Hide Answers' : 'Show Answers'}
          </Button>
          <Button
            onClick={() => window.print()}
            variant="primary"
            size="sm"
            className="bg-neon-blue text-black hover:opacity-90 flex items-center gap-2"
          >
            <Printer size={16} /> Print / Save PDF
          </Button>
        </div>
      </div>

      {/* Printable content */}
      <div className="max-w-3xl mx-auto bg-white text-black p-8 md:p-12 rounded-2xl print:rounded-none print:p-0 shadow-lg print:shadow-none">
        <div className="border-b-2 border-black pb-4 mb-6">
          <div className="flex items-center gap-2 mb-2">
            <FileText size={24} />
            <span className="text-xl font-black">PREPIFY</span>
          </div>
          <h1 className="text-2xl font-black">{quiz.title}</h1>
          <div className="flex gap-3 mt-2 text-sm text-gray-600">
            <span>{quiz.course}</span>
            <span>•</span>
            <span>{quiz.difficulty}</span>
            <span>•</span>
            <span>{quiz.items_count} Questions</span>
          </div>
        </div>

        <ol className="space-y-6">
          {quiz.questions.map((q, i) => (
            <li key={i} className="break-inside-avoid">
              <p className="font-bold mb-2">{i + 1}. {q.question}</p>
              <ul className="ml-5 list-[lower-alpha] space-y-1">
                {q.options.map((opt, j) => {
                  const isAnswer = opt === q.answer;
                  return (
                    <li key={j} className={showAnswers && isAnswer ? 'font-bold text-green-700' : ''}>
                      {opt}{showAnswers && isAnswer ? ' ✓' : ''}
                    </li>
                  );
                })}
              </ul>
              {showAnswers && (
                <p className="mt-2 text-sm text-gray-600 italic border-l-2 border-gray-300 pl-2">{q.explanation}</p>
              )}
            </li>
          ))}
        </ol>

        <div className="mt-8 pt-4 border-t border-gray-300 text-center text-xs text-gray-500">
          Generated by Prepify • {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}
